new QuestionCard('What was the most popular show streamed on Netflix?', ['The Crown', 'Tiger King', 'Lucifer', 'Ozark'], 'Ozark');
new QuestionCard('What was the hottest commodity of 2020?', ['Hand Sanitizer', 'Puzzles', 'Toilet Paper', 'Fitness Equipment'], 'Toilet Paper');
new QuestionCard('What is the proper way to wear a mask?', ['Mask covers nose and mouth and eyes', 'Mask covers nose and mouth and secure it under your chin', 'Mask covers mouth and chin', 'Mask is left in car or at home'], 'Mask covers nose and mouth and secure it under your chin');
new QuestionCard('Bong Joon Ho made history as the first South Korean to win the Best Director Oscar for which movie?', ['Parasite', 'Onward', 'Mulan', 'The Invisible Man'], 'Parasite');
new QuestionCard('What popular DIY coffee went viral?', ['Affogato', 'Doppio Espresso', 'Espresso Ristretto', 'Dalgona Coffee'], 'Dalgona Coffee');
new QuestionCard('What is the name of the virus that caused the pandemic?', ['AREA 51', 'COVID 19', 'Heinekenvirus', 'HCorona 22'], 'COVID 19');
new QuestionCard('What are we nicknaming children who were conceived during the pandemic?', ['Pandemic Babies', 'Maskers', 'Baby Boomers', 'Karens'], 'Pandemic Babies');
new QuestionCard('Who was elected president?', ['Barack Obama', 'Kanye West', 'Donald Trump', 'Joe Biden'], 'Joe Biden');
new QuestionCard('Not known to the area, which winged insect caused alarm when spotted in Washington State?', ['Killer Butterflies', 'Killer Bees', 'Murder Hornets', 'Zombie Moths'], 'Murder Hornets');
new QuestionCard('What was the name of the planet identified by a high school intern at NASA?', ['XI 1200 b', 'R2D2 3000', 'CP4 4000 a', 'TOI 1338 b'], 'TOI 1338 b');
new QuestionCard('Which social media challenge had people trying to defy gravity on Feb 10, 2020?', ['The Broom Challenge', 'The Level Up Challenge', 'The Stand Up Challenge', 'The Plank Challenge'], 'The Broom Challenge');
new QuestionCard('Everyone knows that Carol Baskin killed her husband, but can you remember what his name was?', ['Howard Baskin', 'Joe Lewis', 'Don Lewis', 'Hermit Baskin'], 'Don Lewis');
new QuestionCard('There are seven speakers sprinkled across which country allowing you to broadcast your built up 2020 scream?', ['Ireland', 'Finland', 'New Zealand', 'Iceland'], 'Iceland');
new QuestionCard('Which celebrity was the first to publicly announce they had been tested positive for Coronavirus?', ['Mel Gibson', 'Ellen DeGeneres', 'Larry King', 'Tom Hanks'], 'Tom Hanks');
new QuestionCard('Which leading cartoon character was confirmed as a member of the LGBTQ Community?', ['Curious George', 'Jimmy Neutron', 'BoJack Horseman', 'Spongebob'], 'Spongebob');
new QuestionCard('Videos were released by the Pentagon admitting what are real?', ['Aliens', 'Giants', 'UFOs', 'Underground Cities'], 'UFOs');
new QuestionCard('Who performed the Super Bowl LIV halftime show?', ['The Weekend', 'Shakira and JLO', 'Maroon 5', 'Beyonce and JayZ'], 'Shakira and JLO');
new QuestionCard('Which celebrity NBA player sadly passed away?', ['Kobe Bryant', 'Michael Jordan', 'Shaquille O’Neal', 'Charles Barkley'], 'Kobe Bryant');
new QuestionCard('What was the most Googled recipe in 2020', ['Doubletree Cookie', 'Dole Whip', 'Disney Churro', 'Sourdough Bread'], 'Sourdough Bread');
new QuestionCard('A baby was born from an embryo that was how old?', ['27 years old', '64 years old', '18 years old', '34 years old'], '27 years old');
// testing